from .general_selfcontact_loss import SelfContactLoss
from .selfcontact_optimization_loss import SelfContactOptiLoss
from .selfcontact_optimization_anim_loss import SelfContactOptiAnimLoss
from .selfcontact_optimization_anim_assign_loss import SelfContactOptiAnimAssignLoss